---
title: "analisi preliminare"
author: "MNB"
date: "4/25/2024"
output: html_document
---

# load libraries
```{r}
library(plyr)
library(dplyr)
library(tidyverse)
library(tidyr)
library(naniar)
library(ggplot2)
library(stargazer)
library(brms)
library(sandwich)
library(lmtest)
library(magrittr) # for pipes
library(nnet) # for the multinom()-function
library(MASS) # for the multivariate normal distribution

# The package
library(MNLpred)

# Plotting the predicted probabilities:
library(scales)

```


# Remove lists 
```{r, include=FALSE}
## remove lists
rm(list=ls())
```

# Functions
```{r}
# exclude
'%!in%' <- function(x,y)!('%in%'(x,y))

# Function to scale a variable to the 0-1 range
scale_0_1 <- function(x) {
  (x - min(x, na.rm = TRUE)) / (max(x, na.rm = TRUE) - min(x, na.rm = TRUE))
}


# Define the function to generate a variable chain suitable for a model
gen_formula <- function(dependent_var, var_list) {
  # Concatenate the variable names with " + " as separator
  var_chain <- paste(var_list, collapse = " + ")

  complete_formula <- as.formula(paste(dependent_var, var_chain, sep = " ~ "))

    
  # Return the concatenated variable chain
  return(complete_formula)
}


```


# Import DFs
## Set folders
```{r}
## set url
#desktop_path <- file.path("C:", "Users", "marco", "Desktop")
desktop_path <- file.path("C:", "Users", "krogers", "Nextcloud")
#main_folder_name <- "DFGlobalLab"
main_folder_name <- "Global Solidarity"
sub_folder_name <- "Compiled"

```

## Import Globsol dataset
### 5k
```{r}
# set DF
DF<-c("globsol_20240313_df5k.rds")
# load DF
Df_path <- file.path(desktop_path, main_folder_name, sub_folder_name, DF )
# importing DF 
df_Globsol5k <- readRDS(Df_path)

```

### 50k
```{r}
# set DF
DF<-c("globsol_20240313_df50k.rds")
# load DF
Df_path <- file.path(desktop_path, main_folder_name, sub_folder_name, DF )
# importing DF 
df_Globsol50k <- readRDS(Df_path)

```


### 100k
```{r}
# set DF
DF<-c("globsol_20240313_df100k.rds")
# load DF
Df_path <- file.path(desktop_path, main_folder_name, sub_folder_name, DF )
# importing DF 
df_Globsol100k <- readRDS(Df_path)

```


## Import Independent and control variables
```{r}
# set DF
DF<-c("df_ind_var.rds")
# load DF
Df_path <- file.path(desktop_path, main_folder_name, sub_folder_name, DF )
# importing DF 
df_IndVars <- readRDS(Df_path)

```

# Set dataset for analysis
```{r}
data<-df_Globsol50k
```

# Merge dfs
```{r}
df_full <- left_join(data, df_IndVars, by = c("year" = "year", "iso3c" = "iso3c"))

## remove useless vars
# keep var of interest
df_full <- df_full[ , names(df_full) %!in% c("country.x",
                                            "country.y",
                                            "country_wb",
                                            "disaster")] 
```

# start analysis
## preprocess data
```{r}

## select vars if interest
List<-c("count_HO_lag_1",
        "nat_rents_lag_1",
        "trade_part_lag_1",
        "exp_part_lag_1",
        "impo_part_lag_1",
        "N_donors_lag_1",
        "pop_tot_lag_1",
        "gdp_lag_1",
        "gdp_per_cap_ppp_lag_1",
        "inflation_lag_1",
        "urb_pop_pct_lag_1",
        "trade_lag_1",
        "inf_mort_rate_lag_1",
        "liberal_demo_lag_1",
        "regime_corruption_lag_1",
        "civil_soc_lag_1",
        "best_fat_lag_1",
        "food_export_lag_1",
        "food_import_lag_1",
        "biological_dummy_50k",
        "biological_dummy_lag_1_50k",
        "climatological_dummy_50k",
        "climatological_dummy_lag_1_50k",
        "geophysical_dummy_50k",
        "geophysical_dummy_lag_1_50k",
        "hydrological_dummy_50k",
        "hydrological_dummy_lag_1_50k",
        "meteorological_dummy_50k",
        "meteorological_dummy_lag_1_50k",
        "colony_fra",
        "colony_gbr",
        "colony_oeu",
        "colony_prt",
        "colony_esp",
        "tropical",
        "desert",
        "N_memberships",
        "NS_donors_ratio_lag_1",
        "fuel_income_lag_1",
        "rpe_agri_lag_1.x",
        "rpe_gdp_lag_1.x",
        "rpe_gdp_nonres_lag_1.x")

table(df_full$rpe)

df_model_data <- df_full[ , names(df_full) %in% c(List,"GlobSol","iso3c","year")] 

## drop NAs
#df_model_data <- na.omit(df_model_data)

# List of variable names to scale
#variables_to_scale <- List

# List of variable names to scale
df_scaled<-df_model_data

# log variables
df_scaled$ln_GDP_lag_1<-log(df_scaled$gdp_lag_1)
df_scaled$ln_gdp_per_cap_ppp_lag_1<-log(df_scaled$gdp_per_cap_ppp_lag_1)
df_scaled$ln_pop_tot_lag_1<-log(df_scaled$pop_tot_lag_1)
df_scaled$ln_trade_lag_1<-log(df_scaled$trade_lag_1)
df_scaled$ln_fuel_income_lag_1<-log((1+df_scaled$fuel_income_lag_1))
df_scaled$ln_GDP_lag_1<-log(df_scaled$gdp_lag_1)

# #retain unscaled for model precision checks
# df_scaled$ln_GDP_lag_1_unscaled<-df_scaled$ln_GDP_lag_1
# df_scaled$ln_pop_tot_lag_1_unscaled<-df_scaled$ln_pop_tot_lag_1
# df_scaled$ln_trade_lag_1_unscaled<-df_scaled$ln_trade_lag_1
# df_scaled$ln_fuel_income_lag_1_unscaled<-df_scaled$ln_fuel_income_lag_1
# df_scaled$gdp_lag_1_unscaled<-df_scaled$gdp_lag_1
# df_scaled$pop_tot_lag_1_unscaled<-df_scaled$pop_tot_lag_1
# df_scaled$trade_lag_1_unscaled<-df_scaled$trade_lag_1
# df_scaled$fuel_income_lag_1_unscaled<-df_scaled$fuel_income_lag_1
# df_scaled$ln_gdp_per_cap_ppp_lag_1_unscaled<-df_scaled$ln_gdp_per_cap_ppp_lag_1
# df_scaled$gdp_per_cap_ppp_lag_1_unscaled<-df_scaled$gdp_per_cap_ppp_lag_1
# 
## scale varaibles
#df_scaled$nat_rents_lag_1<-(df_scaled$nat_rents_lag_1)/100
#df_scaled$urb_pop_pct_lag_1<-(df_scaled$urb_pop_pct_lag_1)/100
#df_scaled$tropical<-(df_scaled$tropical)/100
#df_scaled$desert<-(df_scaled$desert)/100
df_scaled$gdp_per_cap_ppp_lag_1<-df_scaled$gdp_per_cap_ppp_lag_1/100

#variables_to_scale <- c("ln_GDP_lag_1","ln_pop_tot_lag_1","ln_trade_lag_1","ln_fuel_income_lag_1",
#                       "gdp_lag_1", "pop_tot_lag_1","trade_lag_1","fuel_income_lag_1",
#                       "ln_gdp_per_cap_ppp_lag_1","gdp_per_cap_ppp_lag_1")
#df_scaled[variables_to_scale] <- lapply(df_scaled[variables_to_scale], scale_0_1)

## set fixed effects
df_scaled$iso3c <- as.factor(df_scaled$iso3c)
df_scaled$year <- as.factor(df_scaled$year)

# Check the distribution of the Globsol variable
table(df_scaled$GlobSol)

#add index column to data frame
df_scaled$index <- 1:nrow(df_scaled)

##
df_scaled$colony<-ifelse(df_scaled$colony_fra==1|
                           df_scaled$colony_gbr==1|
                           df_scaled$colony_oeu==1 |
                           df_scaled$colony_prt==1 |
                           df_scaled$colony_esp==1,1,0)

## disaster count
df_scaled$dis_count<-df_scaled$biological_dummy_50k+df_scaled$climatological_dummy_50k+df_scaled$geophysical_dummy_50k+df_scaled$hydrological_dummy_50k+df_scaled$meteorological_dummy_50k
df_scaled$dis_count_lag_1<-df_scaled$biological_dummy_lag_1_50k+df_scaled$climatological_dummy_lag_1_50k+df_scaled$geophysical_dummy_lag_1_50k+df_scaled$hydrological_dummy_lag_1_50k+df_scaled$meteorological_dummy_lag_1_50k

```

## Export file
```{r}
#saving it
namefile<-"df_full.csv"
folder_path_wb <- file.path(desktop_path, main_folder_name, sub_folder_name, namefile)
write.csv(df_scaled, folder_path_wb, row.names = FALSE,na = "")  # row.names = FALSE to exclude row indices

```


## Set variables
```{r}
# Define the dependent variable and set is as an unordered factors
dependent_var <- "GlobSol"
df_scaled$GlobSol <- factor(df_scaled$GlobSol)  # Ensure it's a factor
# Re-level the target variable to set 4 as the baseline
df_scaled$GlobSol <- relevel(df_scaled$GlobSol, ref = "4")


main_indip <- c("trade_part_lag_1","gdp_per_cap_ppp_lag_1", "nat_rents_lag_1")

econo <- c("trade_lag_1","ln_pop_tot_lag_1","inflation_lag_1")
cof_deve <- c("best_fat_lag_1","urb_pop_pct_lag_1","inf_mort_rate_lag_1")
pol <- c("liberal_demo_lag_1","rpe_agri_lag_1.x")
disaster <- c("dis_count")
disaster_lagged <- c("dis_count_lag_1")

disaser_extended <- c("biological_dummy_50k",
                    "climatological_dummy_50k",
                    "geophysical_dummy_50k",
                    "hydrological_dummy_50k",
                    "meteorological_dummy_50k")

disaser_extended_lag <- c("biological_dummy_lag_1_50k",
                    "climatological_dummy_lag_1_50k",
                    "geophysical_dummy_lag_1_50k",
                    "hydrological_dummy_lag_1_50k",
                    "meteorological_dummy_lag_1_50k")

geo_colonial <-c("tropical","desert","colony")

```


## Run multinomial models
```{r}
# Full controls
Vars<-c(main_indip,econo,pol,cof_deve,geo_colonial,disaster)
full_model_df<- df_scaled[complete.cases(df_scaled[, c(dependent_var,Vars)]), ]
full_model_df <- full_model_df[, c(dependent_var,Vars)]

# baseline model
Vars<-main_indip
# Create the complete formula
complete_formula <-gen_formula(dependent_var,Vars)
# Estimate the multinomial logistic regression model
multinom_model1 <- multinom(complete_formula, data = df_scaled)

# Economic controls
Vars<-c(main_indip,econo)
# Create the complete formula
complete_formula <-gen_formula(dependent_var,Vars)
# Estimate the multinomial logistic regression model
multinom_model2 <- multinom(complete_formula, data = df_scaled)

# Political controls
Vars<-c(main_indip,pol)
# Create the complete formula
complete_formula <-gen_formula(dependent_var,Vars)
# Estimate the multinomial logistic regression model
multinom_model3 <- multinom(complete_formula, data = df_scaled)

# Conflict & Development
Vars<-c(main_indip,cof_deve)
# Create the complete formula
complete_formula <-gen_formula(dependent_var,Vars)
# Estimate the multinomial logistic regression model
multinom_model4 <- multinom(complete_formula, data = df_scaled)

Vars<-c(main_indip,econo,pol,cof_deve)
# Create the complete formula
complete_formula <-gen_formula(dependent_var,Vars)
# Estimate the multinomial logistic regression model
multinom_model4b <- multinom(complete_formula, data = df_scaled)

# Geographic and colonial controls
Vars<-c(main_indip,geo_colonial)
# Create the complete formula
complete_formula <-gen_formula(dependent_var,Vars)
# Estimate the multinomial logistic regression model
multinom_model5 <- multinom(complete_formula, data = df_scaled)

# disaster controls
Vars<-c(main_indip,disaster)
# Create the complete formula
complete_formula <-gen_formula(dependent_var,Vars)
# Estimate the multinomial logistic regression model
multinom_model6 <- multinom(complete_formula, data = df_scaled)

# Full controls
Vars<-c(main_indip,econo,pol,cof_deve,geo_colonial,disaster)
# Create the complete formula
complete_formula <-gen_formula(dependent_var,Vars) 
# Estimate the multinomial logistic regression model
multinom_model7 <- multinom(complete_formula, data = df_scaled)

```

## plot results tables
```{r}
# Create a comparison table with stargazer
stargazer(
  multinom_model1, multinom_model2, 
  multinom_model4b, multinom_model7,
  type = "text",  # or "latex" or "html" for different output formats
  title = "Comparison of Multinomial Models",
  align = TRUE,
  no.space = TRUE,
  digits = 3  # Number of decimal places to display
  #column.labels = c("Model 1", "Model 2", "Model 3")  # Label each model
)
```

## Model precision check
```{r}
#library(texreg)

# All unlogged GDPpc models outperform logged GDPpc models
# Unlog trade, log population outperforms log-log and unlog-unlog combinations
# Exclude corruption - similar to liberal_demo: Including only corruption slightly poorer fit than only liberal_demo, much poorer including both.
# Exclude disaster type - similar to disaster count: Including only type poorer fit than only count, much poorer including both.
# Add RPE (agri), infant mortality, inflation

#screenreg(list(multinom_model7,multinom_model8,multinom_model9,multinom_model10))

```

### probabilities with marginal intervals
```{r}
# Full controls
Vars<-c(main_indip,econo,pol,cof_deve,geo_colonial,disaster)

# Create the complete formula
complete_formula <-gen_formula(dependent_var,Vars) 
# Estimate the multinomial logistic regression model
mod1 <- multinom(complete_formula, data = full_model_df,
                            Hess = TRUE)

gles<-full_model_df

pred1 <- mnl_pred_ova(model = mod1,
                      data = gles,
                      x = "trade_part_lag_1",
                      by = 5,
                      seed = "random", # default
                      nsim = 100, # faster
                      probs = c(0.025, 0.975)) # default

min(full_model_df$trade_part_lag_1)
max(full_model_df$trade_part_lag_1)

pred1$plotdata$GlobSolOrdered <- factor(pred1$plotdata$GlobSol, levels = c("3", "1", "4", "2"))

globsol_labels <- c("1" = "Cosmopolitan",
                    "2" = "Collective Action",
                    "3" = "Post-colonial",
                    "4" = "Communitarian")

ggplot(data = pred1$plotdata, aes(x = trade_part_lag_1, 
                                  y = mean,
                                  ymin = lower, ymax = upper)) +
  scale_fill_manual(values=c("1"="#E41A1C", "2"="#377EB8", "3"="#4DAF4A", "4"="#984EA3"), name="GlobSol",
                    labels=globsol_labels) +
  scale_colour_manual(values=c("1"="#E41A1C", "2"="#377EB8", "3"="#4DAF4A", "4"="#984EA3"), name="GlobSol",
                      labels=globsol_labels) +
  geom_ribbon(aes(fill = GlobSol), alpha = 0.2, colour = NA) +  # Confidence intervals with no border color
  geom_line(aes(colour = GlobSol)) +  # Mean line with color
   facet_wrap(~ GlobSolOrdered, scales = "fixed", ncol = 2, labeller = labeller(GlobSolOrdered = as_labeller(globsol_labels))) +
  scale_y_continuous(labels = percent_format(accuracy = 1)) + # % labels
  scale_x_continuous(breaks = seq(60,240,20)) +
  theme_bw() +
  # theme(
  #   axis.text.x = element_text(angle = 45, hjust = 1),  # Tilt x-axis labels
  #   axis.text.y = element_text(angle = 45, vjust = 1)   # Tilt y-axis labels (if needed)
  # ) +
  labs(y = "Predicted probabilities",
       x = "Number of trade partners")  +
  theme(strip.text = element_text(face = "bold"))

min(full_model_df$gdp_per_cap_ppp_lag_1)
max(full_model_df$gdp_per_cap_ppp_lag_1)


pred1 <- mnl_pred_ova(model = mod1,
                      data = gles,
                      x = "gdp_per_cap_ppp_lag_1",
                      by = 10,
                      seed = "random", # default
                      nsim = 100, # faster
                      probs = c(0.025, 0.975)) # default

pred1$plotdata$GlobSolOrdered <- factor(pred1$plotdata$GlobSol, levels = c("3", "1", "4", "2"))

globsol_labels <- c("1" = "Cosmopolitan",
                    "2" = "Collective Action",
                    "3" = "Post-colonial",
                    "4" = "Communitarian")

ggplot(data = pred1$plotdata, aes(x = gdp_per_cap_ppp_lag_1, 
                                  y = mean,
                                  ymin = lower, ymax = upper)) +
  scale_fill_manual(values=c("1"="#E41A1C", "2"="#377EB8", "3"="#4DAF4A", "4"="#984EA3"), name="GlobSol",
                    labels=globsol_labels) +
  scale_colour_manual(values=c("1"="#E41A1C", "2"="#377EB8", "3"="#4DAF4A", "4"="#984EA3"), name="GlobSol",
                      labels=globsol_labels) +
  geom_ribbon(aes(fill = GlobSol), alpha = 0.2, colour = NA) +  # Confidence intervals with no border color
  geom_line(aes(colour = GlobSol)) +  # Mean line with color
  facet_wrap(~ GlobSolOrdered, scales = "fixed", ncol = 2, labeller = labeller(GlobSolOrdered = as_labeller(globsol_labels))) +
  scale_y_continuous(labels = percent_format(accuracy = 1)) + # % labels
  scale_x_continuous(breaks = seq(0, 600, 50), 
                     labels=seq(0,60,5)) +
  theme_bw() +
  labs(y = "Predicted probabilities",
       x = "GDP per capita ($US PPP, thousands)") +
  theme(strip.text = element_text(face = "bold"))


pred1 <- mnl_pred_ova(model = mod1,
                      data = gles,
                      x = "nat_rents_lag_1",
                      by = 1,
                      seed = "random", # default
                      nsim = 100, # faster
                      probs = c(0.025, 0.975)) # default


pred1$plotdata$GlobSolOrdered <- factor(pred1$plotdata$GlobSol, levels = c("3", "1", "4", "2"))

globsol_labels <- c("1" = "Cosmopolitan",
                    "2" = "Collective Action",
                    "3" = "Post-colonial",
                    "4" = "Communitarian")

ggplot(data = pred1$plotdata, aes(x = nat_rents_lag_1, 
                                  y = mean,
                                  ymin = lower, ymax = upper)) +
  scale_fill_manual(values=c("1"="#E41A1C", "2"="#377EB8", "3"="#4DAF4A", "4"="#984EA3"), name="GlobSol",
                    labels=globsol_labels) +
  scale_colour_manual(values=c("1"="#E41A1C", "2"="#377EB8", "3"="#4DAF4A", "4"="#984EA3"), name="GlobSol",
                      labels=globsol_labels) +
  geom_ribbon(aes(fill = GlobSol), alpha = 0.2, colour = NA) +  # Confidence intervals with no border color
  geom_line(aes(colour = GlobSol)) +  # Mean line with color
  facet_wrap(~ GlobSolOrdered, scales = "fixed", ncol = 2, labeller = labeller(GlobSolOrdered = as_labeller(globsol_labels))) +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +  # % labels
  scale_x_continuous(breaks = seq(0, 50, 5)) +
  theme_bw() +
  labs(y = "Predicted probabilities",
       x = "Natural Resource Rents (% GDP)") +
  theme(strip.text = element_text(face = "bold"))




```
```{r}
library(broom)
library(marginaleffects)
library(ggstance)

ame <- avg_slopes(mod1,variables = main_indip)

ame$term<-ifelse(ame$term=="gdp_per_cap_ppp_lag_1","Per capita GDP",
          ifelse(ame$term=="nat_rents_lag_1", "Natural resource rents",
                 "Trade partners"))


ggplot(ame, aes(x=estimate,y=term,colour=group))+ 
  geom_vline(xintercept=0,linetype="dashed",color = "black", size=0.5)+
  geom_pointrangeh(aes(xmin=conf.low,
                     xmax=conf.high),
    position=position_dodgev(height=0.75))+
  ylab("Independent variables")+xlab("Average marginal effect (95% CI)")+
   scale_colour_manual(values=c("1"="#E41A1C", "2"="#377EB8", "3"="#4DAF4A", "4"="#984EA3"),,name="GlobSol",
                     labels=c("1"="Cosmopolitan",
                              "2"="Collective Action",
                              "3"="Post-colonial",
                              "4"="Communitarian"))+
theme_minimal() + theme(panel.grid.major = element_blank(), panel.grid.minor= element_blank())

```

