---
title: "DV_IV_combine"
author: "MNB"
date: "4/25/2024"
output: html_document
---

## 01 12 2025
# Restart R
```{r}
#.rs.restartR()
```

# load libraries
```{r, include=FALSE}
library(dplyr)
library(tidyverse)
library(tidyr)

```


# Remove lists 
```{r, include=FALSE}
## remove lists
rm(list=ls())
```

# Functions
```{r, include=FALSE}
# exclude
'%!in%' <- function(x,y)!('%in%'(x,y))

# Function to scale a variable to the 0-1 range
scale_0_1 <- function(x) {
  (x - min(x, na.rm = TRUE)) / (max(x, na.rm = TRUE) - min(x, na.rm = TRUE))
}


# Define the function to generate a variable chain suitable for a model
gen_formula <- function(dependent_var, var_list) {
  # Concatenate the variable names with " + " as separator
  var_chain <- paste(var_list, collapse = " + ")

  complete_formula <- as.formula(paste(dependent_var, var_chain, sep = " ~ "))

    
  # Return the concatenated variable chain
  return(complete_formula)
}

```


# Import DFs
## Set folders
```{r}
## set url Marco Nextclod
desktop_path <- file.path("C:", "Users", "marco", "Nextcloud")
#desktop_path <- file.path("C:", "Users", "krogers", "Nextcloud")

main_folder_name <- "Global Solidarity"
sub_folder_name <- "Compiled"

```

## Import Globsol dataset
### 5k
```{r}
# set DF
DF<-c("globsol_df5k_v2_1.rds")
# load DF
Df_path <- file.path(desktop_path, main_folder_name, sub_folder_name, DF )
# importing DF
df_Globsol5k <- readRDS(Df_path)

```

### 50k
```{r}
# set DF
DF<-c("globsol_df50k_v2_1.rds")
# load DF
Df_path <- file.path(desktop_path, main_folder_name, sub_folder_name, DF )
# importing DF 
df_Globsol50k <- readRDS(Df_path)

```

### 50k no assistance
```{r}
# set DF
DF<-c("globsol_df50k_v2_1_no_assistance.rds")
# load DF
Df_path <- file.path(desktop_path, main_folder_name, sub_folder_name, DF )
# importing DF 
df_Globsol50k_noass <- readRDS(Df_path)

```

### 100k
```{r}
# set DF
DF<-c("globsol_df100k_v2_1.rds")
# load DF
Df_path <- file.path(desktop_path, main_folder_name, sub_folder_name, DF )
# importing DF 
df_Globsol100k <- readRDS(Df_path)

```


## Import Independent and control variables
```{r}
# set DF
DF<-c("df_Ind_var_v3_1.rds")
# load DF
Df_path <- file.path(desktop_path, main_folder_name, sub_folder_name, DF )
# importing DF 
df_IndVars <- readRDS(Df_path)

```

# Set dataset for analysis
```{r}
df_DepVars <-df_Globsol5k
#df_DepVars  <-df_Globsol50k
#df_DepVars <-df_Globsol100k
#df_DepVars <-df_Globsol50k_noass

```

# Merge dfs
```{r}
df_full <- left_join(df_DepVars, df_IndVars, by = c("year" = "year", "iso3c" = "iso3c"))

## remove useless vars
# keep var of interest
df_full <- df_full[ , names(df_full) %!in% c("country.x",
                                            "country.y",
                                            "country_wb",
                                            "disaster")] 

```

# start analysis
## preprocess data
```{r}
# Check the distribution of the Globsol variable
table(df_full$GlobSol)

#add index column to data frame
df_full$index <- 1:nrow(df_full)

##
df_full$colony<-ifelse(df_full$colony_fra==1|
                           df_full$colony_gbr==1|
                           df_full$colony_oeu==1 |
                           df_full$colony_prt==1 |
                           df_full$colony_esp==1,1,0)

## create variable last_time: last time a counry experienced th type of solidarity is experiencing now
df_full <- df_full %>%
  arrange(iso3c, year) %>%
  group_by(iso3c) %>%
  mutate(Last_time = {
    last_time <- rep(NA, n())  # Initialize result vector
    for (i in seq_len(n())) {
      current_globsol <- GlobSol[i]
      current_year <- year[i]
      past_rows <- which(GlobSol[1:(i - 1)] == current_globsol)  # Find past occurrences
      if (length(past_rows) > 0) {
        last_time[i] <- current_year - year[max(past_rows)]  # Years since last occurrence
      }
    }
    last_time
  }) %>%
  ungroup()

# Replace 0s with NA in variable X
df_full$Last_time[df_full$Last_time == 0] <- NA

```

## Export file
```{r}
#saving it
#namefile<-"df_full_v3_5000.csv"
#namefile<-"df_full_v3.csv"
#namefile<-"df_full_v3_100000.csv"
#namefile<-"df_full_v3_noass.csv"

## correct names
df_full<-janitor::clean_names(df_full) %>%
  dplyr::select(-dis_ids) %>% dplyr::select(-end_dis_ids)

# folder_path <- file.path(desktop_path, main_folder_name, sub_folder_name, namefile)
# write.csv(df_full, folder_path, row.names = FALSE,na = "")  # row.names = FALSE to exclude row indices

```


## Export slim
```{r}

df_slim <- df_full%>%dplyr::select("glob_sol",
                                   "iso3c",
                                   "year",
                                   "dis_death",
                                   "mil_per_lag_1",
                                   "nat_rents_lag_1",
                                   "gdp_per_cap_ppp_lag_1",
                                   "trade_lag_1",
                                   "pop_tot_lag_1",
                                   "inf_mort_rate_lag_1",
                                   "liberal_demo_lag_1",
                                   "colony",
                                   "oil_rents_lag_1",
                                   "minerals_rents_lag_1",
                                   "gas_rents_lag_1",
                                   "gdp_lag_1",
                                   "best_fat_lag_1",
                                   "commitment_tot_pc_lag_1",
                                   "regio_pol",
                                   "dis_count",
                                   "glob_sol_yearmean",
                                   "norm_agr",
                                   "hum_plus_er_aid_tot")

#saving it
namefile<-"df_full_v4_1_5000.csv"
#namefile<-"df_full_v4_1.csv"
#namefile<-"df_full_v4_1_100000.csv"
#namefile<-"df_full_v4_1_noass.csv"

folder_path <- file.path(desktop_path, main_folder_name, sub_folder_name, namefile)
write.csv(df_slim, folder_path, row.names = FALSE,na = "")  # row.names = FALSE to exclude row indices

```


```{r}

```





