---
title: "Visualizations"
author: "MNB"
date: "2/29/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}

```

# Rm lists
```{r}

```

# Functions
```{r}

```

# Import DF
```{r}
df_NoAg_Aid_Dis= left_join(df_ICWES_dis50k_y, df_aid_sec, by = c("year" = "year", "iso3c" = "iso3c"))
```

# Code GlobSol
```{r}
#drop NA
df_NoAg_Aid_Dis<-Drop_NA(df_NoAg_Aid_Dis, dummy_Hplus_ERaid)
df_NoAg_Aid_Dis<-Drop_NA(df_NoAg_Aid_Dis, dummy_agreement)

df_NoAg_Aid_Dis <- df_NoAg_Aid_Dis %>%
  mutate(GlobSol = case_when(
    dummy_agreement == 1 & dummy_Hplus_ERaid == 1 ~ 1,
    dummy_agreement == 1 & dummy_Hplus_ERaid == 0 ~ 2,
    dummy_agreement == 0 & dummy_Hplus_ERaid == 1 ~ 3,
    dummy_agreement == 0 & dummy_Hplus_ERaid == 0 ~ 4
  ))
```

# Plot GlobSol over time
```{r}
df_t<-df_NoAg_Aid_Dis

df_t$GlobSol <- factor(df_t$GlobSol)
df_t$year <- factor(df_t$year)

# Plotting using ggplot2 with stacked bars and year labels
ggplot(df_t, aes(x = year, fill = GlobSol)) +
  geom_bar(position = "stack") +
  labs(x = "Year", y = "Count", title = "Stacked Distribution of GlobSol Over Years")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+ # Tilting the x-axis labels by 45 degrees
  theme(panel.background = element_blank()) 



```

# Plot GlobSol for specific years
```{r}
df_2006<-subset(df,df$year==2007)


df_g<-df_2006
# List of variables to scale
vars_to_scale <- c("NormAgr", "Hum_plus_ER_aid_tot")

# Scale selected variables to range from 0 to 1
df_g <- df_g
df_g$aid_scaled <- df_g$Hum_plus_ER_aid_tot/100000

xlim<-mean(df_g$year_mean_NormAgr)
ylim<-mean(df_g$year_mean_Hum_plus_ERaid)

# Plot the dataset
ggplot(df_g, aes(x = NormAgr, y = aid_scaled)) +
  geom_point() +
  labs(x = "NormAgr", y = "aid_scaled", title = "Scatter Plot of X1 vs X2")+
  geom_vline(xintercept = xlim, linetype = "dashed", color = "red") +
  geom_hline(yintercept = (ylim/100000), linetype = "dashed", color = "blue")+
  xlim(xlim - 15 , xlim + 45) +  # Adjust some_padding as needed
  ylim((ylim/100000)-800,(ylim/100000)+8000) + # Adjust some_padding as needed
  geom_point(aes(colour = factor(GlobSol)))+
  theme(panel.background = element_blank())+
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray")  

```

# Map GlobSol for specific years
```{r}

```

